version: "3.9"
services:
  puppeteer:
    build: .
    container_name: puppeteer-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000 || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 5
